apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zpbn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zpbn
    app.kubernetes.io/part-of: tkwch-fix-0075-0048-app
  name: devfile-sample-zpbn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zpbn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zpbn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0048-tenant/tkwch-fix-0075-0048-app/devfile-sample-zpbn@sha256:bf9a59259acf1810a22a11c87b39472ff8a2b899fdd8994ed4d1515350b1f5b9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
